const fs = require('fs');
const path = require('path');
const https = require('https');

const ZIP_URL = 'https://gaftp.epa.gov/Air/nei/2023/data_summaries/eis_report_37583_2023NEI_facility_summary.zip';
const METADATA_PATH = path.join(__dirname, '..', 'src', 'lib', 'nei_2023_metadata.json');
const ARCGIS_BASE = 'https://services.arcgis.com/cJ9YHowT8TU7DUyn/ArcGIS/rest/services/Air_Quality_Design_Values_for_Criteria_Pollutants/FeatureServer';

function getGaftpLastModified() {
  return new Promise((resolve, reject) => {
    const req = https.request(ZIP_URL, { method: 'HEAD', timeout: 10000 }, (res) => {
      if (res.statusCode !== 200) {
        reject(new Error(`GAFTP returned status code ${res.statusCode}`));
        return;
      }
      resolve(res.headers['last-modified'] || '');
    });
    req.on('error', reject);
    req.end();
  });
}

async function getArcgisLatestYear() {
  const layerId = 1; // Ozone (representative criteria pollutant)
  const params = new URLSearchParams({
    where: '1=1',
    outFields: 'DVYearText',
    orderByFields: 'DVYearText DESC',
    resultRecordCount: '1',
    f: 'json',
  });
  const url = `${ARCGIS_BASE}/${layerId}/query?${params}`;
  const res = await fetch(url, { signal: AbortSignal.timeout(5000) });
  if (!res.ok) throw new Error(`ArcGIS returned status code ${res.status}`);
  const data = await res.json();
  const features = data.features || [];
  if (features.length > 0 && features[0].attributes?.DVYearText) {
    const yr = parseInt(features[0].attributes.DVYearText);
    if (!isNaN(yr)) return yr;
  }
  throw new Error('Could not parse latest year from ArcGIS response');
}

async function main() {
  console.log('Starting daily data freshness audit...');
  let updateMessages = [];
  let updateNeeded = false;

  // 1. Audit NEI 2023 Point Source Data
  try {
    const remoteModified = await getGaftpLastModified();
    let localModified = '';
    if (fs.existsSync(METADATA_PATH)) {
      const meta = JSON.parse(fs.readFileSync(METADATA_PATH, 'utf8'));
      localModified = meta.lastModified || '';
    }

    console.log(`[NEI 2023] Remote Last-Modified: "${remoteModified}"`);
    console.log(`[NEI 2023] Local Last-Modified:  "${localModified}"`);

    if (remoteModified && localModified !== remoteModified) {
      updateNeeded = true;
      updateMessages.push(`- **NEI 2023 Database Update Available**: The EPA GAFTP server has a newer dataset version.\n  * Remote Last-Modified: \`${remoteModified}\`\n  * Local Last-Modified: \`${localModified || 'None'}\``);
    } else {
      console.log('[NEI 2023] Dataset is up-to-date.');
    }
  } catch (err) {
    console.error('[NEI 2023] Audit failed:', err.message);
  }

  // 2. Audit NAAQS Design Value Years
  try {
    const remoteLatestYear = await getArcgisLatestYear();
    const currentCodeYear = 2024; // Hardcoded baseline check

    console.log(`[NAAQS] ArcGIS Latest Certified Year: ${remoteLatestYear}`);
    console.log(`[NAAQS] Application Baseline Year:    ${currentCodeYear}`);

    if (remoteLatestYear > currentCodeYear) {
      updateNeeded = true;
      updateMessages.push(`- **NAAQS Design Values Update Available**: EPA has certified new Design Value records for the year **${remoteLatestYear}**.\n  * Current Baseline: \`${currentCodeYear}\`\n  * Latest Certified: \`${remoteLatestYear}\``);
    } else {
      console.log('[NAAQS] Design values are up-to-date.');
    }
  } catch (err) {
    console.error('[NAAQS] Audit failed:', err.message);
  }

  // 3. Output results
  if (updateNeeded) {
    const body = `### 📡 Data Update Check Summary\n\nSome EPA data sources have newer versions available. Please run synchronization and rebuild the application to keep the dashboard current:\n\n${updateMessages.join('\n\n')}\n\n---\n*This alert was automatically generated by the daily GitHub Action data check.*`;
    
    fs.writeFileSync(path.join(__dirname, '..', 'update_details.txt'), body, 'utf8');
    console.log('\nUpdates found! Details written to update_details.txt');
    process.exit(10); // Specific exit code to flag that updates are available
  } else {
    console.log('\nAll datasets are currently up-to-date.');
    process.exit(0);
  }
}

main().catch(err => {
  console.error('Audit script failed:', err);
  process.exit(1);
});
